<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.4</version>
		<relativePath/> <!-- 从远程仓库中查找父 POM 文件 -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>commerce</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>wafer_single_electronic_commerce</name>
	<description>wafer_single_electronic_commerce</description>
	<modules>
		<module>admin</module>
		<module>common</module>
		<module>portal</module>
		<module>security</module>
		<module>mgb</module>
		<module>search</module>
	</modules>

	<properties>
		<java.version>17</java.version>
		<spring-boot.version>3.2.4</spring-boot.version>
		<lombok.version>1.18.26</lombok.version>
		<mybatis-plus.version>3.5.3.2</mybatis-plus.version>
		<mysql-connector.version>8.0.33</mysql-connector.version>
		<pagehelper-starter.version>2.1.0</pagehelper-starter.version>
		<druid.version>1.2.21</druid.version>
		<hutool.version>5.8.25</hutool.version>
		<springdoc-openapi.version>2.3.0</springdoc-openapi.version>
		<logstash-logback.version>7.4</logstash-logback.version>
		<jjwt.version>0.9.1</jjwt.version>
		<jaxb-api.version>2.3.1</jaxb-api.version>
		<mybatis-generator.version>1.4.2</mybatis-generator.version>
        <mybatis-spring-boot-starter.version>2.3.0</mybatis-spring-boot-starter.version>
		<mybatis-spring-boot.version>2.2.0</mybatis-spring-boot.version>
		<common.version>1.0-SNAPSHOT</common.version>
		<security.version>1.0-SNAPSHOT</security.version>
		<mgb.version>1.0-SNAPSHOT</mgb.version>
		<swagger-annotations.version>2.2.22</swagger-annotations.version>
		<mybatis-plus.version>3.5.7</mybatis-plus.version>
		<spring-boot-devtools.version>3.2.4</spring-boot-devtools.version>
	</properties>

	<dependencies>
		<!-- Spring Boot Starter -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<version>${spring-boot.version}</version>
		</dependency>

		<!-- Spring Boot Web Starter -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<version>${spring-boot.version}</version>
		</dependency>

		<!-- Spring Boot Test Starter -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<version>${spring-boot.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- Spring Boot Actuator Starter：提供生产环境准备就绪的特性，如度量指标、健康检查和监控 -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<!-- Spring Boot AOP Starter：添加对面向切面编程（AOP）的支持，允许声明式事务管理、方法拦截等 -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>

		<!-- Lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
			<scope>provided</scope>
		</dependency>

		<!--解决JDK 11 兼容性问题-->
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>${jaxb-api.version}</version>
		</dependency>

		<!--Hutool Java工具包-->
		<dependency>
			<groupId>cn.hutool</groupId>
			<artifactId>hutool-all</artifactId>
			<version>${hutool.version}</version>
		</dependency>

		<!-- swagger-->
		<dependency>
        <groupId>io.swagger.core.v3</groupId>
        <artifactId>swagger-annotations</artifactId>
        <version>${swagger-annotations.version}</version>
    	</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<version>${spring-boot-devtools.version}</version>
			<optional>true</optional>
			<scope>true</scope>
		</dependency>



	</dependencies>

	<dependencyManagement>
		<dependencies>

			<dependency>
				<groupId>com.wafer.commerce</groupId>
				<artifactId>common</artifactId>
				<version>${common.version}</version>
			</dependency>

			<dependency>
				<groupId>com.wafer.commerce</groupId>
				<artifactId>security</artifactId>
				<version>${security.version}</version>
			</dependency>

			<dependency>
				<groupId>com.wafer.commerce</groupId>
				<artifactId>mgb</artifactId>
				<version>${mgb.version}</version>
			</dependency>

			<!-- MySQL Connector -->
			<dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<version>${mysql-connector.version}</version>
			</dependency>

			<!--MyBatis分页插件starter-->
			<dependency>
				<groupId>com.github.pagehelper</groupId>
				<artifactId>pagehelper-spring-boot-starter</artifactId>
				<version>${pagehelper-starter.version}</version>
			</dependency>

			<!-- MyBatis Plus Starter -->

			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-spring-boot3-starter</artifactId>
				<version>${mybatis-plus.version}</version>
			</dependency>


			<!--集成druid连接池-->
			<dependency>
				<groupId>com.alibaba</groupId>
				<artifactId>druid-spring-boot-starter</artifactId>
				<version>${druid.version}</version>
			</dependency>

			<!--SpringDoc相关依赖-->
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
				<version>${springdoc-openapi.version}</version>
			</dependency>


			<!--集成logstash-->
			<dependency>
				<groupId>net.logstash.logback</groupId>
				<artifactId>logstash-logback-encoder</artifactId>
				<version>${logstash-logback.version}</version>
			</dependency>

			<!--JWT(Json Web Token)登录支持-->
			<dependency>
				<groupId>io.jsonwebtoken</groupId>
				<artifactId>jjwt</artifactId>
				<version>${jjwt.version}</version>
			</dependency>

			<dependency>
				<groupId>org.mybatis.spring.boot</groupId>
				<artifactId>mybatis-spring-boot-starter</artifactId>
				<version>${mybatis-spring-boot.version}</version>
			</dependency>

			<dependency>
				<groupId>org.mybatis.generator</groupId>
				<artifactId>mybatis-generator-core</artifactId>
				<version>${mybatis-generator.version}</version>
			</dependency>

<!--			<dependency>-->
<!--				<groupId>org.springframework.boot</groupId>-->
<!--				<artifactId>spring-boot-devtools</artifactId>-->
<!--				<version>${spring-boot-devtools.version}</version>-->
<!--			</dependency>-->




		</dependencies>
	</dependencyManagement>

	<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
				</plugin>
			</plugins>
	</build>

<!--	&lt;!&ndash;使用aliyun的镜像源提升依赖下载速度&ndash;&gt;-->
<!--	<repositories>-->
<!--		<repository>-->
<!--			<id>aliyunmaven</id>-->
<!--			<name>aliyun</name>-->
<!--			<url>https://maven.aliyun.com/repository/public</url>-->
<!--		</repository>-->
<!--		<repository>-->
<!--			<id>central2</id>-->
<!--			<name>central2</name>-->
<!--			<url>https://repo1.maven.org/maven2/</url>-->
<!--		</repository>-->
<!--	</repositories>-->

<!--	&lt;!&ndash;使用aliyun的镜像源提升插件下载速度&ndash;&gt;-->
<!--	<pluginRepositories>-->
<!--		<pluginRepository>-->
<!--			<id>aliyunmaven</id>-->
<!--			<name>aliyun</name>-->
<!--			<url>https://maven.aliyun.com/repository/public</url>-->
<!--		</pluginRepository>-->
<!--		<pluginRepository>-->
<!--			<id>central2</id>-->
<!--			<name>central2</name>-->
<!--			<url>https://repo1.maven.org/maven2/</url>-->
<!--		</pluginRepository>-->
<!--	</pluginRepositories>-->

</project>