FROM eclipse-temurin:17-jdk
COPY wafer_commerce_admin.jar /usr/local/wafer/program/wafer_commerce_backend/
WORKDIR /usr/local/wafer/program/wafer_commerce_backend/
CMD ["java", "-jar", "wafer_commerce_admin.jar"]